### ISSUE TITLE
"Queries" wiki page issues

### ISSUE THREAD

**Issue by jumarko** [Datomic/mbrainz-sample#11]
1. In section [Running the Queries](https://github.com/Datomic/mbrainz-sample/wiki/Queries#running-the-queries), there's a typo (probably from previous version of page): '(e.g. the string "Lupe Fiasco" in the example above).'
It should be: '(e.g. the string "Janis Joplin" in the example above).'

2. In section [Fulltext](https://github.com/Datomic/mbrainz-sample/wiki/Queries#fulltext)  the text description 'Let's find all of the tracks with the word "nevermore" in the title.' says "nevermore" but "always" is used later in text and in the query ('Query args' subsection).

3. In section [Graph walk](https://github.com/Datomic/mbrainz-sample/wiki/Queries#graph-walk) the text description 'Let's find Paul McCartney's collaboration network to a depth of 2.' says "Paul McCartney" but later in text and in the query "George Harrison" is used.

**Comment by dchelimsky** [comment]
Fixed. Thanks!
