### ISSUE TITLE
Importing into new datomic dev-local setup?

### ISSUE THREAD

**Issue by avocade** [Datomic/mbrainz-sample#14]
Is this still possible, or do you have to jump through some hoops? :) Can't find any `bin/datomic` executables in the new dev-local install.

https://docs.datomic.com/cloud/dev-local.html

**Comment by Glassonion** [comment]
@avocade You can import mbrainz into dev local using the client importer (https://github.com/Datomic/mbrainz-importer)
You would need to update the deps.edn file to include dev-local (https://docs.datomic.com/cloud/dev-local.html#using) and specify the :dev-local server type in the manifest used for the import.

I will look into providing an example in that repository in the near future.

**Comment by Glassonion** [comment]
@avocade The mbrainz-subset db is also included in the database samples zip file provide here: https://docs.datomic.com/cloud/examples.html#datomic-samples

**Comment by avocade** [comment]
Nice, thanks!
