### ISSUE TITLE
wrong doc for :artist/type (copy/pasted from :artist/name) 

### ISSUE THREAD

**Issue by avodonosov** [Datomic/mbrainz-sample#3]
The :artist/type attribute has doc copied from the :artist/name attribute - "The artist's name for use in sorting, e.g. Beatles, The".

Most likely :artist/type is some enum, right, with values :artist.type/person, and some others?

**Comment by benkamphaus** [comment]
@avodonosov  Thanks for reporting. This has now been fixed in the master schema, but will not be yet reflected in the mbrainz subset backup. -B
