### ISSUE TITLE
Incorrect docstring for :artist/type attribute?

### ISSUE THREAD

**Issue by loganlinn** [Datomic/mbrainz-sample#4]
This docstring for `:artist/type` seems nonsensical. Appears to be copied version of `:artist/sortName` attribute's docstring. Guessing it should be something like, `"Enum, one of: ..."`

https://github.com/Datomic/mbrainz-sample/blob/e0e810eb131e68a5a428e6c4ce6ba4b059bb65be/schema.edn#L66

**Comment by benkamphaus** [comment]
@loganlinn Thanks for reporting. This has now been fixed in the master schema, but will not be yet reflected in the mbrainz subset backup. -B
