### ISSUE TITLE
Can't restore db

### ISSUE THREAD

**Issue by wambat** [Datomic/mbrainz-sample#5]
For some reasons i (as a datomic noob) can't restore tutorial db 
```
~/dist/datomic-pro-0.9.5130/bin/datomic restore-db file:///home/leuser/work/clojure/tutorials/dod/mbrainz-1968-1973/ datomic:dev://localhost:4334/mbrainz-1968-1973
Copied 0 segments, skipped 0 segments.
Copied 631 segments, skipped 0 segments.
Copied 935 segments, skipped 0 segments.
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: :restore/read-failed Unable to read 546abffa-c4cf-461e-aea5-2f0ec83c7de3_00000000000000A {:db/error :restore/read-failed, :key "546abffa-c4cf-461e-aea5-2f0ec83c7de3_00000000000000A"}
```

**Comment by caluml** [comment]
A few of us also have the same problem.
It seems to be that Linux users can't, but OS X users can.

**Comment by naglafar** [comment]
yeah same problem on ubuntu 14.04

**Comment by changa** [comment]
> yeah same problem on ubuntu 14.04

+ 1

**Comment by mt3593** [comment]
Same issue for me:
Linux 3.13.0-37-generic #64-Ubuntu SMP x86_64 GNU/Linux

Tried with both: 
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
and
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)

On datomic-pro-0.9.5130 and datomic-free-0.9.5130

**Comment by mt3593** [comment]
I have also tried with:
datomic-pro-0.9.5078
Copied 0 segments, skipped 0 segments.
Copied 584 segments, skipped 0 segments.
Copied 994 segments, skipped 0 segments.
:failed

datomic-pro-0.9.5052
Copied 0 segments, skipped 0 segments.
Copied 565 segments, skipped 0 segments.
Copied 994 segments, skipped 0 segments.
:failed

both version of java mentioned above where tested, still fails.

**Comment by mt3593** [comment]
Looks like its a odd backup issue..
Works with the http://s3.amazonaws.com/mbrainz/datomic-mbrainz-1968-1973-backup-2014-11-04.tar

So as a work around:
wget http://s3.amazonaws.com/mbrainz/datomic-mbrainz-1968-1973-backup-2014-11-04.tar -O mbrainz.tar
tar -xvf mbrainz.tar

Using Java(TM) SE Runtime Environment (build 1.7.0_55-b13) and datomic-pro-0.9.5130

**Comment by mt3593** [comment]
If you have issues with restore/collision when doing the work around just delete the data directory in datomic-pro-0.9.5130 home directory

**Comment by tokomakoma123** [comment]
I've encountered the same problem using datomic-free. I deleted the datomic-free-0.9.5130 and unziped installer zipped file again then it worked fine. I've reported this problem to the datomic group 
on the google groups.

**Comment by benkamphaus** [comment]
Hello all,

Thanks for reporting. The repository has been updated to link to a new version of the mbrainz sample backup which restores correctly cross-platform.
