### ISSUE TITLE
AbstractRelease seems to be missing entirely

### ISSUE THREAD

**Issue by kosiakk** [Datomic/mbrainz-sample#9]
I've tried both the latest backup and the one from 2014-11-17.
There is not a single entity referenced from `:release/abstractRelease`

```[:find ?artist
 :in $
 :where
 [_ :abstractRelease/artists ?artist]
]``` returns empty set

```[:find ?name
 :in $
 :where
 [_ :abstractRelease/name ?name]
]``` too

Should it be deleted from the schema then?

**Comment by Glassonion** [comment]
Hi Alexander,

The `:release/abstractRelease` data are present in the full mbrainz dataset, but are removed from the 1968-1973 subset database.

I will clarify this in the repository.

-Marshall
